Exodus-Privacy/website

Readme.md
This is a first proposal for a Readme.md file for this repository
=> First proposal for a ReadMe file

content/page/events.en.md, content/page/events.fr.md
I updated the events page, in french and english
=> events update

content/post/comptabilite-2019.en.md, content/post/comptabilite-2019.fr.md
Added accouting for june in accounting pages (both en and fr)
=> Adding accountin june in both english and french page

content/post/comptabilite-2019.en.md, content/post/comptabilite-2019.fr.md
Accounting update for july 2019
=> Accouting update for july 2019

content/post/comptabilite-2019.en.md, content/post/comptabilite-2019.fr.md
Add accounting for August 2019 both language
=> Accounting august 2019 both language

content/page/press.en.md
Changed the order of the English Press section to appear first, on file `press.en.md`
=> change order of english press to be first on press.en.md

content/page/press.en.md, content/page/press.fr.md
Separate press links by year on files: `press.en.md` and `press.fr.md`
=> Press links format

content/page/contribute.en.md, content/page/contribute.fr.md
Heyo! I've updated the IRC link on the Contribute page in French and English to use the URL listed in #32
=> Update IRC URL

content/post/comptabilite-2017.en.md, content/post/comptabilite-2018.en.md, content/post/comptabilite-2019.en.md, content/post/comptabilite-2019.fr.md
Fixes #4 
Translating the remaining accounting pages into English
**Note:** there are extra changes because my text editor (rightly) removes unwanted spaces :)
=> Translate Accounting pages into EN

content/page/supporters.en.md, content/page/supporters.fr.md
Now the partners are sorted as well (F-droid before Yale Privacy Lab) :)
=> Sorted the partners in alphabetical order

content/post/comptabilite-2019-2020.en.md, content/post/comptabilite-2019-2020.fr.md
New post for september accouning
=> Addind accouting (new method) posts for september

config.toml, themes/hugo-bootstrap/layouts/partials/base/footer.html
Add Github link to site footer (English and French)
=> add Github link to site footer

content/post/tracking-trackers.en.md, content/post/tracking-trackers.fr.md
=> add blog post about ETIP

content/page/who.en.md, content/page/who.fr.md
=> Broken link on Who page

content/page/events.en.md, content/page/events.fr.md
=> events modification

content/page/events.en.md, content/page/events.fr.md
I added the Ping events and put the past ones into the "past ones" category :)
=> modification of the events page

content/page/faq.en.md, content/page/faq.fr.md
- Add link to information pages in exodus (trackers & permissions)
- Add table of contents with the list of questions
- Add lines to separate questions
=> Rework of FAQ page

content/page/what.en.md, content/page/what.fr.md
Hi!
Here are two commits to help improve the "what" page:
- one for improving the language of the page
- one to try and fix the size of the Peertube logo, so it aligns with the Youtube one
Hope this helps!
=> Improvements to the English version of the "what" page

content/page/who.en.md, content/page/who.fr.md
Very minor change to update the link to my own GitHub account (which changed a couple of weeks ago)
=> Correct link for pnu's github account

.gitignore, content/page/what.en.md, content/page/what.fr.md
=> Adding a reference to the Better Understand page

content/post/AG2020.en.md
=> translation of AG2020

content/post/Bilan2020.fr.md
=> fixing some typos

content/page/press.en.md, content/page/press.fr.md
* French press articles for beginning of 2021 
* Missing date for "le code a changé"
* Missing white lines
=> Add french press articles for beginning of 2021 

content/page/who.en.md, content/page/who.fr.md
=> Update who page

content/post/Anniversaire.fr.md, content/post/Assemblee-generale2018.fr.md, content/post/exodus-facebook.fr.md, content/post/forum-and-browser-add_on.fr.md, content/post/new-trackers-in-exodus-platform.fr.md
In some posts the `•` glyphe was used as a middle dot, this PR replace it by a real middle dot `·`
=> Fix middle dot in all posts

content/page/contribute.en.md, content/page/contribute.fr.md, content/page/who.en.md, content/page/who.fr.md
Because Matrix is too complicated to join for new peoples, we add 2-click join IRC links
=> Update IRC links on contribute and who pages

content/page/press.en.md, content/page/press.fr.md
Adds new article for 2021 end of year
* https://balkaninsight.com/2021/12/30/cracking-covid-the-balance-between-public-health-and-private-data/
* https://telanganatoday.com/cyber-talk-making-social-media-secure-for-women
=> Add new articles for 2021

content/page/contribute.en.md, content/page/contribute.fr.md
Just remove the bitcoin wallet access, according to the board decisions. Reorganise the contribute page to have something looks correct.
=> Remove bitcoin donation from the contribute page

content/post/kitpeda.fr.md
J'ai enlevé la fin du billet, suite aux réunions en ligne.
=> modif billet de blog suite reunion

content/page/contribute.en.md, content/page/contribute.fr.md
As already [documented on the forum](https://forum.exodus-privacy.eu.org/topic/19/organisation-de-exodus-privacy/2).
=> Add membership process on contribute page

content/page/what.en.md, content/page/what.fr.md
=> Add missing app on Google Play Store explanation

content/page/press.en.md, content/page/press.fr.md
Hello,
I added links of recent articles to the pages for press in French and English.
Let me know if you have questions,
Have a good evening!
Lea
=> Added recent publications to press

content/page/who.en.md, content/page/who.fr.md
* Updates member list
* Updates mastodon links
* Adds `rel=me` for mastodon links (for verification)
=> feat: Update who page

content/post/bonne-annee-2023.en.md, content/post/bonne-annee-2023.fr.md
Ajout du post de bonne année rédigé par Lovis_IX et sa traduction en anglais
=> Bonne annee 2023

content/page/contribute.en.md, content/page/contribute.fr.md, content/page/faq.en.md, content/page/faq.fr.md, content/page/what.en.md, content/page/what.fr.md, content/page/what.ru.md
This instance is no longer available
=> remove all mentions of the old exodus privacy peertube instance

themes/hugo-bootstrap/layouts/partials/base/header.html, themes/hugo-bootstrap/static/assets/css/custom.css
=> feat (header): Highlight page name on the navigation bar!

content/page/privacy-policy.fr.md
Todo:
- Update android app to open right url following language of device.
=> Add privacy policy in french

content/page/privacy-policy.en.md, content/page/privacy-policy.fr.md
Fixes #216 
Let's find the best formulation
=> Fix privacy policy
